DEFAULT:
  publication:
    bbc:
      city: London, UK
    currency_from: GBP
    currency_to: USD

RSS_FEEDS:
  bbc: 'http://feeds.bbci.co.uk/news/rss.xml'
  cnn: 'http://rss.cnn.com/rss/edition.rss'
  fox: 'http://feeds.foxnews.com/foxnews/latest'
  iol: 'http://rss.iol.io/iol/news'
  fivethirtyeight: 'https://fivethirtyeight.com/all/feed'
